pub mod auth_routes;
pub mod contratos_captacion_routes;
pub mod entidades_routes;
pub mod persona_routes;
pub mod poliza_routes;
pub mod reportes_routes;
pub mod test_routes;
pub mod trabajo_routes;
pub mod ubicacion_routes;
