ALTER TABLE domicilios
ALTER COLUMN cp DROP NOT NULL,
ALTER COLUMN colonia DROP NOT NULL,
ALTER COLUMN calle_id DROP NOT NULL,
ALTER COLUMN entre_calle_id DROP NOT NULL,
ALTER COLUMN y_calle_id DROP NOT NULL,
ALTER COLUMN numero_exterior DROP NOT NULL;
