CREATE TYPE clasificacion_finalidad AS ENUM (
    'comercio',
    'consumo',
    'vivienda'
);

CREATE TABLE finalidades (
    id_finalidad SERIAL PRIMARY KEY,
    grupo_finalidad INTEGER NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    clasificacion clasificacion_finalidad,
    aplica_iva BOOLEAN NOT NULL,
    tcredito_id VARCHAR(5) NOT NULL,
    tcredito VARCHAR(50),
    FOREIGN KEY (grupo_finalidad) REFERENCES grupos_finalidad(id_grupo_finalidad) ON DELETE RESTRICT
);

INSERT INTO finalidades (id_finalidad, grupo_finalidad, nombre, clasificacion, aplica_iva, tcredito_id, tcredito) VALUES
(10001,	1,	'COMPRA DE MAT. Y M.O.(AMPL.)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10002,	1,	'MEJORAS, MANT. O REMOD.DE CASA',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10003,	1,	'ENGANCHE Y/O AB.DE CASA O TERR',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10004,	1,	'COMPRA INT. DE CASA O TERRENO',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10005,	1,	'PAGO DE ESCRIT.Y/O IMP.PREDIAL',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10006,	1,	'INTRODUC.DE SERV.(PAV.AGUA,LUZ',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10007,	1,	'COMPRA DE MUEB.L.BLANCA Y NEGR',	NULL,	FALSE,	'208BM',	'Adquisicion de bienes muebles'),
(10008,	1,	'COMPRA TRANSP. USO PARTICULAR',	NULL,	FALSE,	'207CA',	'AUTOMOTRIZ'),
(10009,	1,	'REPARAC.Y MTTO. BIENES DE C.D.',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10010,	1,	'GASTOS EDUCATIVOS',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10011,	1,	'GASTOS DEL HOGAR(ALIM,ROPA,CA)',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10012,	1,	'GASTOS MEDICOS',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10013,	1,	'GASTOS DE ESPARC. Y RECREAC.',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10014,	1,	'EVENTOS SOCIALES',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10015,	1,	'PAGO DE SERV. PUB.(LUZ,AG.TEL)',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10016,	1,	'PAGO DE IMPUESTOS',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10017,	1,	'HONORARIOS PROFES.(NO MEDICOS)',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10018,	1,	'PAGOS DE DA¥OS A TERC.X ACCID.',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10019,	1,	'GASTOS FUNERARIOS',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10020,	1,	'PAGO SEG.(VIDA,TRANSP.CASAHAB)',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10021,	1,	'CRED.REFAC.SERV.TRANSP.PUBLICO',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10022,	1,	'HABILITACION AVIO P.EMP.DE SER',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10023,	1,	'COMERC.(ADQ.DE BIENES P. VENTA',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10024,	1,	'REFACC.PARA LA IND.(MAQ.Y EPO)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10025,	1,	'CRED.HAB.Y/O AVIO IND(MAT.PRIM',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10026,	1,	'CRED.REF.AGRIC.(TRACT.Y UT.LAB',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10027,	1,	'CRED.HAB.Y/O AVIO AGRIC(SEMYFE',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10028,	1,	'REFACC.PARA LA GAN.(SEM,PIE C)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10029,	1,	'CRED.HAB.Y/O AVIO GAN.(ENGORDA',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10030,	1,	'CRED. PARA LA VIVIENDA',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10031,	1,	'MUEBLES, LINEA BLANCA Y ELECTRONICA',	NULL,	FALSE,	'208BM',	'Adquisicion de bienes muebles'),
(10032,	1,	'SERV.,BIENES DE USO TEMP.O IMP',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10033,	1,	'PRODUC.DE BIENES O SERVICIOS',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10034,	1,	'PAGO DE TARJETAS DE CREDITO',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10035,	1,	'PAGO DE HIPOTECAS',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10036,	1,	'COMERC.DE BIENES(SISTEMA FIN.)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10037,	1,	'CRED.REFACC.(SISTEMA FINANC.)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10038,	1,	'DE HABIL.Y/O AVIO(SISTEMA FIN)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10039,	1,	'GTOS.PERS. O DE CONSUMO(FIN.IN',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10040,	1,	'CRE.HIPOTECARIOS(FIN. INFORM.)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10041,	1,	'CRED.COMERC.DE BIENES(FIN.INF)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10042,	1,	'CRED.REFACCIONARIOS(FIN.INF.)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10043,	1,	'CRED.DE HABIL.Y/O AVIO(FIN.IN)',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10044,	1,	'PAGO DE HIPOTECAS',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10045,	1,	'PRESTAMO DE EXSOCIO',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10046,	1,	'GASTOS DE VIAJE',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10047,	1,	'COMPRA DE MAT. Y M.O.(AMPL.)',	NULL,	TRUE,	'102IS',	'Interes Social'),
(10048,	1,	'MEJORAS, MANT. O REMOD.DE CASA',	NULL,	TRUE,	'102IS',	'Interes Social'),
(10049,	1,	'ENGANCHE Y/O AB.DE CASA O TERR',	NULL,	TRUE,	'102IS',	'Interes Social'),
(10050,	1,	'COMPRA INT. DE CASA O TERRENO',	NULL,	TRUE,	'102IS',	'Interes Social'),
(10052,	1,	'PAGO DEUDAS FUERA DE LA CAJA',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10053,	1,	'CRED.REFAC.SERV.TRANSP.PUBLICO',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10054,	1,	'HABILITACION AVIO P.EMP.DE SER',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10055,	1,	'COMERC.(ADQ.DE BIENES P. VENTA',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10056,	1,	'REFACC.PARA LA IND.(MAQ.Y EPO)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10057,	1,	'CRED.HAB.Y/O AVIO IND(MAT.PRIM',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10058,	1,	'CRED.REF.AGRIC.(TRACT.Y UT.LAB',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10059,	1,	'CRED.HAB.Y/O AVIO AGRIC(SEMYFE',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10064,	1,	'REFACC.PARA LA GAN.(SEM,PIE C)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10065,	1,	'CRED.HAB.Y/O AVIO GAN.(ENGORDA',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10068,	1,	'CRED. PARA LA VIVIENDA',	NULL,	TRUE,	'102IS',	'Interes Social'),
(10069,	1,	'BIENES DE CONSUMO DURADERO',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10070,	1,	'PAGO DE INT. MENSUALMENTE',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10071,	1,	'PAGO AL VENCIMIENTO',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10072,	1,	'SERV.,BIENES DE USO TEMP.O IMP',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10073,	1,	'PRODUC.DE BIENES O SERVICIOS',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10074,	1,	'COMERC.DE BIENES(SISTEMA FIN.)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10075,	1,	'CRE.HIPOTECARIOS(FIN. INFORM.)',	NULL,	TRUE,	'102IS',	'Interes Social'),
(10076,	1,	'CRED.COMERC.DE BIENES(FIN.INF)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10077,	1,	'CRED.DE HABIL.Y/O AVIO(FIN.IN)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10078,	1,	'CRED.REFACC.(SISTEMA FINANC.)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10079,	1,	'CRED.REFACCIONARIOS(FIN.INF.)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10080,	1,	'DE HABIL.Y/O AVIO(SISTEMA FIN)',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10081,	1,	'APOYO PROCAMPO',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10082,	1,	'COMPRA DE MAT. Y M.O.(AMPL.)',	NULL,	TRUE,	'101MR',	'Media y Residencial'),
(10083,	1,	'MEJORAS, MANT. O REMOD.DE CASA',	NULL,	TRUE,	'101MR',	'Media y Residencial'),
(10084,	1,	'ENGANCHE Y/O AB.DE CASA O TERR',	NULL,	TRUE,	'101MR',	'Media y Residencial'),
(10085,	1,	'COMPRA DE CASA O TERRENO',	NULL,	TRUE,	'101MR',	'Media y Residencial'),
(10086,	1,	'CRED. PARA LA VIVIENDA',	NULL,	TRUE,	'101MR',	'Media y Residencial'),
(10087,	1,	'CRE.HIPOTECARIOS(FIN. INFORM.)',	NULL,	TRUE,	'101MR',	'Media y Residencial'),
(10088,	1,	'CRED.REFAC.SERV.TRANSP.PUBLICO',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10089,	1,	'HABILITACION AVIO P.EMP.DE SER',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10090,	1,	'COMERC.(ADQ.DE BIENES P. VENTA',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10091,	1,	'REFACC.PARA LA IND.(MAQ.Y EPO)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10092,	1,	'CRED.HAB.Y/O AVIO IND(MAT.PRIM',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10093,	1,	'CRED.REF.AGRIC.(TRACT.Y UT.LAB',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10094,	1,	'CRED.HAB.Y/O AVIO AGRIC(SEMYFE',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10095,	1,	'REFACC.PARA LA GAN.(SEM,PIE C)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10096,	1,	'CRED.HAB.Y/O AVIO GAN.(ENGORDA',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10097,	1,	'BIENES DE CONSUMO DURADERO',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10098,	1,	'PRODUC.DE BIENES O SERVICIOS',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10099,	1,	'COMERC.DE BIENES(SISTEMA FIN.)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10100,	1,	'CRED.COMERC.DE BIENES(FIN.INF)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10101,	1,	'CRED.DE HABIL.Y/O AVIO(FIN.IN)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10102,	1,	'CRED.REFACC.(SISTEMA FINANC.)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10103,	1,	'CRED.REFACCIONARIOS(FIN.INF.)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10104,	1,	'DE HABIL.Y/O AVIO(SISTEMA FIN)',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10105,	1,	'APOYO PROCAMPO',	NULL,	TRUE,	'302OP',	'Operaciones Prendarias'),
(10106,	1,	'CRED.REFAC.SERV.TRANSP.PUBLICO',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10107,	1,	'HABILITACION AVIO P.EMP.DE SER',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10108,	1,	'COMERC.(ADQ.DE BIENES P. VENTA',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10109,	1,	'REFACC.PARA LA IND.(MAQ.Y EPO)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10110,	1,	'CRED.HAB.Y/O AVIO IND(MAT.PRIM',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10111,	1,	'CRED.REF.AGRIC.(TRACT.Y UT.LAB',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10112,	1,	'CRED.HAB.Y/O AVIO AGRIC(SEMYFE',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10113,	1,	'REFACC.PARA LA GAN.(SEM,PIE C)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10114,	1,	'CRED.HAB.Y/O AVIO GAN.(ENGORDA',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10115,	1,	'BIENES DE CONSUMO DURADERO',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10116,	1,	'PRODUC.DE BIENES O SERVICIOS',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10117,	1,	'COMERC.DE BIENES(SISTEMA FIN.)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10118,	1,	'CRED.COMERC.DE BIENES(FIN.INF)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10119,	1,	'CRED.DE HABIL.Y/O AVIO(FIN.IN)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10120,	1,	'CRED.REFACC.(SISTEMA FINANC.)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10121,	1,	'CRED.REFACCIONARIOS(FIN.INF.)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10122,	1,	'DE HABIL.Y/O AVIO(SISTEMA FIN)',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10123,	1,	'APOYO PROCAMPO',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10125,	1,	'MI PYME',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10126,	1,	'AGROPECUARIO',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10127,	1,	'AGROPECUARIO',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10128,	1,	'PROGRAMA MAIZ Y FRIJOL',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10129,	1,	'PROGRAMA MAIZ Y FRIJOL',	NULL,	TRUE,	'301OQ',	'Operaciones Quirografarias'),
(10130,	1,	'APOYO PROCAMPO',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10131,	1,	'CREDITOS LIQUIDES SCAPS',	NULL,	TRUE,	'306PL',	'Prestamios de Liquidez a Otras Ent'),
(10132,	1,	'GASTOS EDUCATIVOS NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10133,	1,	'GASTOS DEL HOGAR(ALIM,ROPA,CA) NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10134,	1,	'GASTOS MEDICOS NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10135,	1,	'GASTOS DE ESPARC. Y RECREAC. NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10136,	1,	'EVENTOS SOCIALES NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10137,	1,	'PAGO DE SERV. PUB.(LUZ,AG.TEL) NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10138,	1,	'PAGO DE IMPUESTOS NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10139,	1,	'GASTOS FUNERARIOS NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10140,	1,	'PAGO SEG.(VIDA,TRANSP.CASAHAB) NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10141,	1,	'MUEBLES, LINEA BLANCA Y ELECTRONICA NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10142,	1,	'GASTOS DE VIAJE NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10143,	1,	'GTOS.PERS. O DE CONSUMO NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10144,	1,	'MEJORAS, MANT. O REMOD.DE CASA NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10145,	1,	'REPARAC.Y MTTO. BIENES DE C.D. NM',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10146,	1,	'HAB. Y AVIO INDUSTRIA DE LA TRANS. Y SERVICIOS',	NULL,	TRUE,	'301PQ',	NULL),
(10147,	1,	'HAB. Y AVIO INDUSTRIA DE LA TRANS. Y SERVICIOS',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10148,	1,	'INVENTARIO Y EXTRACCIÓN DE PRODUCTOS FORESTALES.',	NULL,	TRUE,	'301PQ',	NULL),
(10149,	1,	'INVENTARIO Y EXTRACCIÓN DE PRODUCTOS FORESTALES.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10150,	1,	'MANEJO Y TRANSFORMACIÓN DE PRODUCTOS FORESTALES.',	NULL,	TRUE,	'301PQ',	NULL),
(10151,	1,	'MANEJO Y TRANSFORMACIÓN DE PRODUCTOS FORESTALES.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10152,	1,	'PAGO DE SUELDOS Y GASTOS REL. CON LA PRODUCCIÓN.',	NULL,	TRUE,	'301PQ',	NULL),
(10153,	1,	'PAGO DE SUELDOS Y GASTOS REL. CON LA PRODUCCIÓN.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10154,	1,	'COMPRA Y/O INST. DE EQ. DE BOMBEO Y SIST. RIEGO.',	NULL,	TRUE,	'301PQ',	NULL),
(10155,	1,	'COMPRA Y/O INST. DE EQ. DE BOMBEO Y SIST. RIEGO.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10156,	1,	'ACOND. Y MEJORAS DE TERR. DEST. AL CULTIVO.',	NULL,	TRUE,	'301PQ',	NULL),
(10157,	1,	'ACOND. Y MEJORAS DE TERR. DEST. AL CULTIVO.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10158,	1,	'EST. DE PLANTACIONES Y/O CULTIVOS PERENNES.',	NULL,	TRUE,	'301PQ',	NULL),
(10159,	1,	'EST. DE PLANTACIONES Y/O CULTIVOS PERENNES.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10160,	1,	'GASTOS DE LABOR DE CULTIVO Y PAGO DE JORNALES AGR.',	NULL,	TRUE,	'301PQ',	NULL),
(10161,	1,	'GASTOS DE LABOR DE CULTIVO Y PAGO DE JORNALES AGR.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10162,	1,	'ADQUISICIÓN DE VEHÍCULOS DE USO PRODUCTIVO.',	NULL,	TRUE,	'301PQ',	NULL),
(10163,	1,	'ADQUISICIÓN DE VEHÍCULOS DE USO PRODUCTIVO.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10164,	1,	'PAGO DE RENTA DE PARCELAS.',	NULL,	TRUE,	'301PQ',	NULL),
(10165,	1,	'PAGO DE RENTA DE PARCELAS.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10166,	1,	'REPARACIÓN Y MANTENIMIENTO DE EQUIPO DE BOMBEO.',	NULL,	TRUE,	'301PQ',	NULL),
(10167,	1,	'REPARACIÓN Y MANTENIMIENTO DE EQUIPO DE BOMBEO.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10168,	1,	'CONSTRUCCIÓN, AMPL. O REMODELACIÓN DE INST.',	NULL,	TRUE,	'301PQ',	NULL),
(10169,	1,	'CONSTRUCCIÓN, AMPL. O REMODELACIÓN DE INST.',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(10170,	1,	'PAGO TAR. CRED., DEUDAS CON AGENTES FORM. FINANC.',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10171,	1,	'PAGO TAR. CRED., DEUDAS CON AGENTES FORM. FINANC.',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10172,	1,	'PAGO SEG. DIV. (VIDA, TRANS., CASA, AGRI., ETC.)',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10173,	1,	'PAGO SEG. DIV. (VIDA, TRANS., CASA, AGRI., ETC.)',	NULL,	FALSE,	'206CN',	'NOMINA'),
(10174,	1,	'ADQ. REFACCIONES. Y REP. DE MAQ. Y EQU. DE TRAN.',	NULL,	FALSE,	'202CP',	'Creditos Personales'),
(10175,	1,	'ADQ. REFACCIONES. Y REP. DE MAQ. Y EQU. DE TRAN.',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo'),
(10176,	1,	'ADQUISICION DE PARCELAS O TERRENOS USO PRODUCTIVO',	NULL,	TRUE,	'301PQ',	NULL),
(10177,	1,	'ADQUISICION DE PARCELAS O TERRENOS USO PRODUCTIVO',	NULL,	TRUE,	'307OC',	'Otros Creditos Comerciales'),
(99999,	1,	'DESOCUPADA',	NULL,	FALSE,	'205OC',	'Otros Creditos de Consumo');
