CREATE TABLE maneras_enterarse (
    id_manera_enterarse SERIAL PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL
);

INSERT INTO maneras_enterarse (nombre) VALUES
('RECOMENDACIÓN (FAMILIAR, CONOCIDO, AMIGO)'),
('POR EVENTO QUE LA CAJA REALIZÓ (REUNIÓN, APOYO, FE'),
('POR PUBLICIDAD VISTA (FOLLETO, BARDA, ANUNCIO, PAR'),
('POR LOS SERVICIOS QUE OFRECE (CURSOS, APOYOS, BECA'),
('POR VISITA, LLAMADA, PLÁTICA DEL PERSONAL DE LA CAJA'),
('POR ANUNCIO EN REDES SOCIALES O MEDIOS DIGITALES ('),
('POR MEDIO MASIVOS (TELEVISIÓN, RADIO, PERIFONEO)'),
('POR RECOMENDACIÓN DE UNA ENTIDAD GUBERNAMENTAL'),
('POR INICIATIVA PROPIA (CONOCIMIENTO DE LAS OFICINA'),
('OTRO');

