ALTER TABLE domicilios
ALTER COLUMN cp SET NOT NULL,
ALTER COLUMN colonia SET NOT NULL,
ALTER COLUMN calle_id SET NOT NULL,
ALTER COLUMN entre_calle_id SET NOT NULL,
ALTER COLUMN y_calle_id SET NOT NULL,
ALTER COLUMN numero_exterior SET NOT NULL;