CREATE TABLE ramas (
    id_rama SERIAL PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL
);

INSERT INTO ramas (nombre) VALUES 
    ('AGRICULTURA'),
    ('GANADERIA'),
    ('FORESTAL'),
    ('PESCA'),
    ('OTROS SECTORES PRODUCTIVOS');

CREATE TABLE subramas (
    id_subrama SERIAL,
    rama INTEGER NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    FOREIGN KEY (rama) REFERENCES ramas(id_rama) ON DELETE RESTRICT
);

INSERT INTO subramas (id_subrama, rama, nombre) VALUES 
(101,	1,	'ANUALES - GRANOS ALIMENTICIOS'),
(102,	1,	'ANUALES - OLEAGINOSAS         '),
(103,	1,	'ANUALES - FORRAJES            '),
(104,	1,	'ANUALES - HORTALIZAS          '),
(105,	1,	'ANUALES - INDUSTRIALES        '),
(106,	1,	'ANUALES - OTROS               '),
(107,	1,	'PERENNES - ESTABLECIMIENTO    '),
(108,	1,	'PERENNES - MANTENIMIENTO      '),
(109,	1,	'FRUTALES - ESTABLECIMIENTO    '),
(110,	1,	'FRUTALES - MANTENIMIENTO      '),
(111,	1,	'ORNAMENTALES (CORTE INTERPERIE)'),
(112,	1,	'ORNAMENTALES (CORTE INVERNADERO)'),
(113,	1,	'PLANTAS EN MACETA INTERPERIE'),
(114,	1,	'PLANTAS EN MACETA INVERNADERO'),
(999,	1,	'OTRAS SUBRAMAS'),
(201,	2,	'BOVINO                        '),
(202,	2,	'PORCICULTURA                  '),
(203,	2,	'AVICULTURA                    '),
(204,	2,	'APICULTURA                    '),
(205,	2,	'CAPRINO                       '),
(206,	2,	'CUNICULTURA                   '),
(207,	2,	'OVINO                         '),
(208,	2,	'GANADERIA DIVERSIFICADA       '),
(999,	2,	'OTRAS SUBRAMAS'),
(301,	3,	'EXTRACCION                    '),
(302,	3,	'PRODUCTOS NO MADERABLES       '),
(303,	3,	'PLANTACIONES FORESTALES'),
(999,	3,	'OTRAS SUBRAMAS'),
(401,	4,	'CAPTURA -PESCA RIBERE?A'),
(402,	4,	'CAPTURA - PESCA DE ALTURA     '),
(403,	4,	'CAPTURA - PESCA DE MEDIANA ALTURA'),
(404,	4,	'ACUACULTURA INTENSIVA         '),
(405,	4,	'ACUACULTURA SEMINTENSIVA      '),
(406,	4,	'OTRAS ACTIVIDADES PESQUERAS   '),
(999,	4,	'OTRAS SUBRAMAS'),
(499,	4,	'OTRAS SUBRAMAS PESCA'),
(516,	5,	'MICROCREDITO RURAL'),
(501,	5,	'PRESERVACION Y MEJORAMIENTO AMBIENTAL'),
(502,	5,	'ECOTURISMO                    '),
(503,	5,	'MINERALES METALICOS           '),
(504,	5,	'MINERALES NO METALICOS        '),
(505,	5,	'ARTESANIAS                    '),
(506,	5,	'TEXTILES PRENDAS DE VESTIR Y CUERO'),
(507,	5,	'PAPELERIA LIBRERIA IMPRENTA Y EDIITORIALES'),
(508,	5,	'PRODUCTOS DE CAUCHO Y PLASTICO'),
(509,	5,	'CONSTRUCCION DE VIVIENDA Y SERVICIOS COMUNITARIOS'),
(510,	5,	'ELECTRICIDAD, GAS Y AGUA'),
(511,	5,	'RESTAURANTES Y HOTELES'),
(512,	5,	'TRANSPORTE ALMACENAMIENTO Y COMUNICACIONES'),
(513,	5,	'SERVICIOS COMUNALES SOCIALES Y PERSONALES'),
(999,	5,	'OTRAS SUBRAMAS'),
(515,	5,	'OTRAS INDUSTRIAS Y SERVICIOS'),
(514,	5,	'PEQUEÑO COMERCIO'),
(599,	5,	'OTRAS SUBRAMAS SECTORES PRODUCTIVOS');


