CREATE TABLE programas (
    id_programa SERIAL PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL
);

INSERT INTO programas (nombre) VALUES ('PROGRAMA ORDINARIO');

CREATE TABLE tipos_credito (
    id_tipo_credito SERIAL PRIMARY KEY,
    clave VARCHAR(8),
    nombre VARCHAR(40)
);

INSERT INTO tipos_credito (clave, nombre) VALUES
(NULL, NULL),
('0', NULL),
('001CN', 'SOLICITUD NORMAL'),
('001CP', 'CARTERA PASIVA FIRA'),
('001LC', 'LINEA DE CREDITO'),
('001RE', 'SOLICITUD DE REESTRUCTURACION'),
('001RN', 'RENOVACION POR AMPLIACION'),
('002CN', 'SOBRE-PRESTAMO'),
('002CP', 'CARTERA PASIVA BANCA COMERCIAL'),
('002LC', 'CREDITO EN CUENTA CORRIENTE'),
('002RN', 'RENOVACION NUEVO CREDITO'),
('1', NULL),
('2', NULL);


