pub mod auth_schemas;
pub mod contratos_captacion_schemas;
pub mod entidades_schemas;
pub mod persona_schemas;
pub mod poliza_schemas;
pub mod prestamo_schemas;
pub mod reportes_schemas;
pub mod trabajo_schemas;
pub mod ubicacion_schemas;
