### Crear poliza  (Necesario tener una cuenta iniciada)
POST http://localhost:8000/api/poliza/nueva HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzEzOTk4NDQwLCJleHAiOjE3MTQwMDIwNDB9.Ihs5AqCcXmaUa181-3xZl3Z8bSRLEuZ9EgE_oJl8iYE
Content-Type: application/json

{
  "tipo": "Diarixo",
  "sucursal": 1,
  "concepto": "Concepto 11"
}

### Crear poliza de tipo egreso  (Necesario tener una cuenta iniciada y enviar los datos de una poliza de egreso)
POST http://localhost:8000/api/poliza/nueva HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzEzOTk4NDQwLCJleHAiOjE3MTQwMDIwNDB9.Ihs5AqCcXmaUa181-3xZl3Z8bSRLEuZ9EgE_oJl8iYE
Content-Type: application/json

{
  "tipo": "Egreso",
  "sucursal": 1,
  "concepto": "Concepto 11",
  "poliza_egreso": {
    "beneficiario": "Beneficiario 4",
    "banco": 8,
    "cheque": "Cheque 1"
  }
}
