### Prueba de que funciona la API
GET http://localhost:8000/api HTTP/1.1

### Se registra un usuario en la base de datos
POST http://localhost:8000/api/auth/register HTTP/1.1
content-type: application/json

{
  "usuario": "dgox14",
  "email": "dgox14@gmail.com",
  "contraseña": "123"
}

### Se inicia sesion
POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{
  "usuario": "dgox14",
  "contraseña": "123"
}

### Se cierra sesion
GET http://localhost:8000/api/auth/logout HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzEzMzY3NzM2LCJleHAiOjE3MTMzNzEzMzZ9.xHmLIgWF-XgI2W8vHwWtCQe9mHzxj3eHktrwP2a3tGs

### Se devuelve un usuario
GET http://localhost:8000/api/users/me HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzEzMzY3NzM2LCJleHAiOjE3MTMzNzEzMzZ9.xHmLIgWF-XgI2W8vHwWtCQe9mHzxj3eHktrwP2a3tGs

### Crear calle
POST http://localhost:8000/api/calle/nueva HTTP/1.1
content-type: application/json

{
  "nombre": "De la Malinche",
  "tipo": "P1"
}

### Crear calle
GET http://localhost:8000/api/calle/buscar/?palabras=roble HTTP/1.1