### Prueba de que funciona la API
GET http://localhost:8000/api HTTP/1.1

### Se registra un usuario en la base de datos
POST http://localhost:8000/api/auth/registro HTTP/1.1
content-type: application/json

{
  "usuario": "dgox24",
  "email": "dgox24@gmail.com",
  "contraseña": "123"
}

### Se inicia sesion
POST http://localhost:8000/api/auth/inicio_sesion HTTP/1.1
content-type: application/json

{
  "usuario": "dgox14",
  "contraseña": "123"
}

### Se cierra sesion
GET http://localhost:8000/api/auth/cerrar_sesion HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzEzNDc0NTMxLCJleHAiOjE3MTM0NzgxMzF9.DB9y8FPRciGh5oaYlRPWNxpL9LowPXJZwEa5XWASZmE

### Se devuelve un usuario
GET http://localhost:8000/api/usuarios/actual HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzEzNDc0NTMxLCJleHAiOjE3MTM0NzgxMzF9.DB9y8FPRciGh5oaYlRPWNxpL9LowPXJZwEa5XWASZmE

### Crear calle
POST http://localhost:8000/api/calle/nueva HTTP/1.1
content-type: application/json

{
  "nombre": "De la Malinche",
  "tipo": "calle"
}

### Buscar calle
GET http://localhost:8000/api/calle/buscar/?palabra=roble&limite=3 HTTP/1.1

### Crear domicilio
POST http://localhost:8000/api/domicilio/nuevo HTTP/1.1
content-type: application/json

{
  "cp": "38940",
  "colonia": "Centro",
  "calle_id": 10000001474,
  "entre_calle_id": 10000001846,
  "y_calle_id": 10000002369,
  "numero_exterior": "18",
  "numero_interior": "1"
}

### Crear sucursal
POST http://localhost:8000/api/sucursal/nueva HTTP/1.1
content-type: application/json

{
  "nombre": "Sucursal 2",
  "encargado": 2,
  "domicilio": 1  
}